# Generated by Django 4.0.4 on 2022-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(default='intro', help_text=' Required', verbose_name='intro'),
        ),
    ]
